### ISSUE TITLE
Seed Data Setup for Dev Env

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/yaus#20]
**Is your feature request related to a problem? Please describe.**
Right now there is no see data for the DB but it would improve DX a lot of there is a starting data that someone can play around with.

**Describe the solution you'd like**
`yarn insert-seed-data` should add seed data.

**Comment by daminimehra** [comment]
@ChakshuGautam  pls assign me this issue. I would like to work on this Issue.

**Comment by yuvrajsab** [comment]
Yaus already has a script that does exactly that. `npx prisma db seed`
