### ISSUE TITLE
Failing test in monorepo

### ISSUE THREAD

**Issue by Nazi-pikachu** [Samagra-Development/yaus#54]
**Describe the bug**
Tests are failing in the **monorepo**.

**To Reproduce**
1. Clone the monorepo
2. Install dependencies
3. Run `yarn test api`

**Expected behavior**
The test should pass in the monorepo

**Screenshots**
![image](https://github.com/Samagra-Development/yaus/assets/63303757/d800eb99-4261-4670-8b06-44f4f60f6e8a)

**Desktop (please complete the following information):**
 -  OS: Windows 10
 -  chrome
 -  Version : 113.0.5672.94

**Additional context**
There are two prime reason for failing test
1. Prisma client imports are breaking
2.  PostHog project api key is mandatory to pass

**Comment by Nazi-pikachu** [comment]
@Maintainers
Can anyone please help me out with this, I am trying to intergrate the code written in the previous edition of C4GT to the current monrepo but the test are failings.
CC: @ChakshuGautam

**Comment by yuvrajsab** [comment]
hey @Nazi-pikachu have you generated the Prisma client before running the tests?

**Comment by Nazi-pikachu** [comment]
Hi @yuvrajsab 
Thanks for pointing it out, earlier i was not generating Prisma client however after generating prisma client as well same tests are failing. 
Can you give more context about the whole process you follow before running tests. It would be very helpful.
PS: i have followed this for generating prisma client [Link to doc](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client)

**Comment by yuvrajsab** [comment]
hey, @Nazi-pikachu I have just run the tests using `yarn test api` and they are all passing. And no Posthoh API key is not necessary to run the test I have put there a dummy API key and API host and it is still passing.
```env
POSTHOG_API_KEY=adasdsad
POSTHOG_API_HOST=https://example.com
```
![image](https://github.com/Samagra-Development/yaus/assets/27115069/6ac5d6b8-3e4e-4c60-a4f9-9e2cbbd4c1b7)

**Comment by Nazi-pikachu** [comment]
Thanks @yuvrajsab 
Its now passing all the test cases by taking a dummy api key.
