### ISSUE TITLE
Eventual Consistency in Click Count

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/yaus#6]
Update the click count in DB every 30 seconds and update the redis `incr` to 0. Set the key to be locked when updating the cllcks. This will lead to slower API response for that one API call at that point of time.

**Comment by yuvrajsab** [comment]
is anyone picking this issue?

**Comment by yuvrajsab** [comment]
just checked and this has been already done. @ChakshuGautam should we close this issue?

**Comment by yuvrajsab** [comment]
closed via #83
