### ISSUE TITLE
Cron Job Failing at specific time

### ISSUE THREAD

**Issue by Nazi-pikachu** [Samagra-Development/yaus#82]
**Describe the bug**
I have observed current cron jobs are failing at around 1 A.M IST.

**To Reproduce**
1. Its hard to reproduce it since i have observed this only at specific time around 12 - 1AM.

**Expected behavior**
Ideally cron job should work fine and sync our clicks in db

**Screenshots**
![image](https://github.com/Samagra-Development/yaus/assets/63303757/cbbc6c20-960c-4212-a97f-4edb96dcab49)

**Additional context**
The reason for cron jobs failing at only specific time could be due to the way cron jobs is scheduled in YAUS
Additional testing would be required to confirm this bug.

**Comment by yuvrajsab** [comment]
Is it still relevant?

**Comment by Nazi-pikachu** [comment]
@yuvrajsab I don't think so since we have removed the cron job to update the click count

**Comment by yuvrajsab** [comment]
We removed this cronjob so it is not relevant now.
