### ISSUE TITLE
Add Frontend Admin using React-Admin

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/yaus#9]
Setup [React-Admin](https://marmelab.com/react-admin/) as the base setup for URL management.
The code can be divided into two parts
1. `api` instead of `src`
2. `admin` for admin interface
3. `web` for frontend (home pages etc)

**Comment by ChakshuGautam** [comment]
Hey @tushar5526 please use the [monorepo branch](https://github.com/Samagra-Development/yaus/tree/monorepo). I have setup the basic skeleton of the admin for you to start working on it.

**Comment by tushar5526** [comment]
Hey @ChakshuGautam, the admin interface refers to the interface that a user gets when he registers and creates an organization or is it the interface that we the product owner will have to see and manage all the registered users, projects etc.

**Comment by daminimehra** [comment]
please, assign me this issue. I would like to work on this Issue.
